# python scripts/collect_dataset_on_device.py -cn collect_dataset

input_dir: /mnt/mirflickr/all
input_file_ext: jpg

# can pass existing folder to continue measurement
output_dir: null
output_file_ext: png

# files to measure
n_files: 15
start_idx: 0

# timing
runtime: null   # in hours
start_delay: null   # how much time (in minutes) to wait before starting

# measurement parameters
dummy: False    # simply copy file to output folder for testing

# ideal image levels
max_level: 254
min_level: 200
max_tries: 6

masks: null   # for multi-mask measurements
recon: null   # parameters for reconstruction (for debugging purposes, not recommended to do during actual measurement as it will significantly increase the time)

# -- display parameters
display:
  output_fp: "~/LenslessPiCam_display/test.png"
  # default to this screen: https://www.dell.com/en-us/work/shop/dell-ultrasharp-usb-c-hub-monitor-u2421e/apd/210-axmg/monitors-monitor-accessories#techspecs_section
  screen_res: [1920, 1200]   # width, height
  image_res: null    # useful if input images don't have the same dimension, set it to this 
  pad: 0
  hshift: 0
  vshift: -10
  brightness: 80   # max brightness
  rot90: 3
  delay: 2    # to allow picture to display
  landscape: False    # whether to force landscape

capture:
  measure_bg: False # measure bg every x images, set False if not measuring background
  bg_fp: "black_background"
  framerate: 10
  skip: False    # to test looping over displaying images
  config_pause: 3
  iso: 100
  res: null
  down: 8
  exposure: 0.02    # min exposure
  awb_gains: [1.9, 1.2]  # red, blue
  # awb_gains: null
  fact_increase: 2   # multiplicative factor to increase exposure
  fact_decrease: 1.5