# python scripts/data/upload_dataset_huggingface.py -cn upload_multilens_mirflickr_ambient
defaults:
  - upload_dataset_huggingface
  - _self_

repo_id: "Lensless/MultiLens-Mirflickr-Ambient"
n_files:
test_size: 0.15

# # -- to match TapeCam dataset content distribution, and same light distribution in train/test
# split: 100   # "first: first `nfiles*test_size` for test, `int`: test_size*split for test (interleaved) as if multimask with this many masks

lensless:
  dir: /dev/shm/all_measured_20240813-183259
  ambient: True
  ext: ".png"

lensed:
  dir: /root/LenslessPiCam/data/mirflickr/mirflickr
  ext: ".jpg"

files:
  psf: data/multilens_psf.png
  measurement_config: data/collect_dataset_background_multilens.yaml
