# python scripts/data/upload_diffusercam_huggingface.py
hydra:
  job:
    chdir: True    # change to output folder

repo_id: "bezzam/DiffuserCam-Lensless-Mirflickr-Dataset"
normalize: False
# repo_id: bezzam/DiffuserCam-Lensless-Mirflickr-Dataset-NORM
# normalize: True

dir_diffuser: "DiffuserCam_mirflickr/dataset/diffuser_images"
dir_lensed: "DiffuserCam_mirflickr/dataset/ground_truth_lensed"
psf_fp: "DiffuserCam_mirflickr/psf.tiff"
hf_token: null
file_ext: ".npy"
n_files: null
n_jobs: 8     # for parallelizing conversion to PNG
