# python scripts/measure/analyze_measured_dataset.py
hydra:
  job:
    chdir: True    # change to output folder

dataset_path: null
desired_range: [10, 255]
saturation_percent: 0.05
delete_bad: False
n_files: null
start_idx: null
