sensor: ardu_708
bayer: False
fn: data/awbcal/paper_bayer_lights_on
exp: 0.5
config_pause: 2
# {'off': 0, 'auto': 1, 'sunlight': 2, 'cloudy': 3,
# 'shade': 4, 'tungsten': 5, 'fluorescent': 6, 
# 'incandescent': 7, 'flash': 8, 'horizon': 9}
sensor_mode: "0"
rgb: False
gray: True
iso: 100
sixteen: True   # whether 16 bits or 8 (from Bayer data)
legacy: False 
down: null
res: null
nbits_out: 10
awb_gains: [1,1] #can also set null
# awb_gains: [1.45, 2.62]   # red, blue

#--rg 2.4 --bg 2.0