sensor: ardu_708
bayer: False
fn: data/psf/temporarytest
exp: 0.01
config_pause: 2
# {'off': 0, 'auto': 1, 'sunlight': 2, 'cloudy': 3,
# 'shade': 4, 'tungsten': 5, 'fluorescent': 6, 
# 'incandescent': 7, 'flash': 8, 'horizon': 9}
sensor_mode: "0"
rgb: False
gray: False
greenscale: True
iso: 100
sixteen: False   # whether 16 bits or 8 (from Bayer data)
legacy: False 
down: null
res: null
nbits_out: 10
awb_gains: [1,1] #can also set 1,1 for disable gain.
# awb_gains: [1.45, 2.62]   # red, blue
# gains with monitor testing--rg 1.52 --bg 2.63

#--rg 2.4 --bg 2.0