# python scripts/measure/remote_capture.py -cn capture_rpi_gs
defaults:
  - demo
  - _self_

output: rpi_gs_capture   # output folder for results
save: True
plot: True

rpi:
  username: null
  hostname: null
  python: ~/LenslessPiCam/lensless_env/bin/python

capture:
  sensor: rpi_gs
  exp: 0.2
  bayer: True
  legacy: False   # must be False for rpi_gs
  rgb: False
  gray: False
  down: null
  awb_gains: null
  nbits_out: 10
  nbits: 10   # 8 or 10 for global shutter
