defaults:
  - demo
  - _self_

  
gamma: 2.2  # for plotting PSF

display:
  image_res: [900,-1]   # negative value to set according to other dimension
  vshift: -26

capture:
  legacy: True
  bayer: True
  rgb: True
  down: 4
  awb_gains: [1.8, 1.1]

recon:
  gamma: null
  downsample: 4
  dtype: float32
  use_torch: True
  torch_device: cuda:0
  algo: fista

  fista:
    n_iter: 300

  admm:
    n_iter: 10

postproc:
  # crop in percent to extract region of interest
  # set to null to skip
  crop_hor: [0.29, 0.67]
  crop_vert: [0.22, 0.78]