defaults:
  - demo
  - _self_

plot: False
  
display:
  psf: 10

capture:
  exp: 1
  gray: False
  awb_gains: [2.0, 1.1]
  nbits_out: 8
  nbits: 8
  legacy: False
  rgb: False

  bayer: False
  down: 4
