# python scripts/measure/digicam_example.py
hydra:
  job:
    chdir: True    # change to output folder

rpi:
  username: null
  hostname: null

# mask parameters
psf: null   # if not provided, simulate with parameters below
mask:
  fp: null  # provide path, otherwise generate with seed
  seed: 0
  # defaults to configuration used for this dataset: https://huggingface.co/datasets/bezzam/DigiCam-Mirflickr-SingleMask-25K
  # ie this config: configs/collect_mirflickr_singlemask.yaml
  shape: [54, 26]
  center: [57, 77]

# measurement parameters
capture:
  fp: null
  exp: 0.5
  sensor: rpi_hq
  script: ~/LenslessPiCam/scripts/measure/on_device_capture.py
  iso: 100
  config_pause: 1
  sensor_mode: "0"
  nbits_out: 8
  nbits_capture: 12
  legacy: True
  gray: False
  fn: raw_data
  bayer: True
  awb_gains: [1.6, 1.2]
  rgb: True
  down: 8
  flip: True

# reconstruction parameters
recon:
  torch_device: 'cpu'
  n_iter: 100    # number of iterations of ADMM

simulation:
  use_waveprop: True
  deadspace: True
  scene2mask: 0.3
  mask2sensor: 0.002
  gamma: null    # just for saving