# for Telegram
token: null
whitelist: []
idle: False     # run without processing commands
time_offset: 7200  # offset in seconds to correct for time difference
setup_fp: null

# usernames and IP address
rpi_username: null
rpi_hostname: null
rpi_lensed_username: null
rpi_lensed_hostname: null

# can pre-load PSF so it doesn't have to be loaded and resize at each reconstruction
# psf: null
# -- digicam (simulated)
psf:
  sensor: rpi_hq
  device: adafruit
  mask_shape: [54, 26]
  mask_center: [57, 77]
  flipud: True
  downsample: 4
# -- measured PSF
  fp: null
# psf:
#   # https://drive.switch.ch/index.php/s/NdgHlcDeHVDH5ww?path=%2Fpsf
#   fp: data/psf/tape_rgb_31032023.png
#   # fp: data/psf/tape_rgb.png  # wrong
#   downsample: 4
gamma: 1.5  # for plotting PSF

# which hydra config to use and available algos
config_name: demo
default_algo: admm   # note that unrolled requires GPU
# supported_algos: ["fista", "admm", "unrolled"]
supported_algos: ["fista", "admm"]

# images: https://drive.switch.ch/index.php/s/NdgHlcDeHVDH5ww?path=%2Foriginal
supported_inputs: ["mnist", "thumb", "face", "tree"]


# overlaying logos on the reconstruction
# images: https://drive.switch.ch/index.php/s/NdgHlcDeHVDH5ww?path=%2Foriginal
overlay:
  alpha: 60

  img1: null

  img2:
    fp: data/original/lcav_white.png
    scaling: 0.2
    position: [382,25]

  img3:
    fp: data/original/epfl_white.png
    scaling: 0.23
    position: [374,75]


files:
  mnist:
    fp: data/original/mnist_3.png
    exposure: 0.05
    brightness: 100
  thumb: 
    fp: data/original/thumbs_up.png
    exposure: 0.04
    brightness: 80
  face:
    fp: data/original/face.jpg
    exposure: 0.02
    brightness: 80
  tree:
    fp: data/original/tree.png
    exposure: 0.08
    brightness: 100
