hydra:
  job:
    chdir: True    # change to output folder


files:
  original: data/celeba_mini/000019.jpg
  #original: data/original/mnist_3.png

save: True
use_torch: False
  
simulation:
  object_height: 0.3
  # these distance parameters are typically fixed for a given PSF
  scene2mask: 40e-2
  mask2sensor: 4e-3
  # see waveprop.devices
  sensor: "rpi_hq"
  snr_db: 20
  # Downsampling for PSF
  downsample: 8

  # max val in simulated measured (quantized 8 bits)
  max_val: 230

  image_format: rgb   # rgb, grayscale, bayer_rggb, bayer_bggr, bayer_grbg, bayer_gbrg

  flatcam: False   # only supported if mask.type is "MURA" or "MLS"


mask:
  type: "MLS"    # "MURA", "MLS", "FZA", "PhaseContour"

  # Coded Aperture (MURA or MLS)
  #flatcam_method: 'MLS'
  n_bits: 8 # e.g. 8 for MLS, 99 for MURA
  
  # Phase Contour
  noise_period: [16, 16]
  refractive_index: 1.2
  phase_mask_iter: 10

  # Fresnel Zone Aperture
  radius: 0.32e-3


recon:

  algo: "admm"   # tikhonov or admm

  tikhonov:
    reg: 3e-4

  admm:
    n_iter: 20
    disp_iter: 2
    # Hyperparameters
    mu1: 1e-6
    mu2: 1e-5
    mu3: 4e-5
    tau: 0.0001