# python scripts/recon/train_learning_based.py -cn tapecam_ambient
defaults:
  - tapecam
  - _self_

wandb_project: tapecam_ambient

# Dataset
files:
  dataset: Lensless/TapeCam-Mirflickr-Ambient
  image_res: [600, 600]

alignment:
  # when there is no downsampling
  top_left: [85, 185]  # height, width
  height: 178

reconstruction:
  # direct_background_subtraction: True
  # learned_background_subtraction: [8,16,32,64]   # apply UNetRes to background before subtraction
  unetres_input_background: True   # whether to input background to UNetRes
