sensor: arducam_708
bayer: True
fn: test
exp: 0.02
config_pause: 2
sensor_mode: "0"
rgb: False
gray: False
iso: 100
sixteen: False
legacy: False
down: null
res: null
nbits_out: 10
nbits: 10
awb_gains: null

output: imx708_capture   # output folder for results
save: True
plot: True

# Specify output directory
output_dir: data/captures/imx708

rpi:
  username: null
  hostname: null
  python: ~/LenslessPiCam/lensless_env/bin/python

camera:
  red_gain: null
  blue_gain: null 