# python scripts/recon/digicam.py
defaults:
  - defaults
  - _self_

dataset: mirflickr_single_25k   # for loading model, "mirflickr_single_25k" or "mirflickr_multi_25k"
cache_dir: null #/dev/shm


### object to reconstruct

# Uncomment and comment others
idx: 1    # index from test set to reconstruct
fn: null  # if not null, download this file from https://huggingface.co/datasets/bezzam/DigiCam-Mirflickr-SingleMask-25K/tree/main

# # - box (Uncomment and comment others)
# fn: raw_box.png 
# rotate: False
# alignment:
#   dim: [190, 260]
#   top_left: [145, 130]

# # - plush animals (Uncomment and comment others)
# fn: raw_stuffed_animals.png     
# rotate: False
# alignment:
#   dim: [200, 280]
#   top_left: [115, 120]

### 

# - Learned reconstructions: see "lensless/recon/model_dict.py"
# --- dataset: mirflickr_single_25k
# model: TrainInv+Unet8M_wave
# model: MMCN4M+Unet4M_wave
# model: MWDN8M_wave
# model: U5+Unet8M_wave
# model: Unet8M+U5_wave
# model: Unet4M+TrainInv+Unet4M_wave
# model: Unet2M+MMCN+Unet2M_wave
# model: Unet4M+U5+Unet4M_wave
# model: Unet4M+U10+Unet4M_wave
model: Unet4M+U5+Unet4M_wave_psfNN

# # --- dataset: mirflickr_multi_25k
# model: Unet4M+U5+Unet4M_wave

# # -- for ADMM with fixed parameters
# model: admm
# n_iter: 100

device: cuda:0
n_trials: 10   # to get average inference time
save: True