# python scripts/recon/multilens_ambient.py
defaults:
  - defaults
  - _self_

cache_dir: /dev/shm
psf: null  # default to dataset PSF

# ## - Uncomment to reconstruct from dataset (screen capture)
# idx: 1    # index from test set to reconstruct
# fn: null  # if not null, set local path or download this file from https://huggingface.co/datasets/Lensless/MultiLens-Mirflickr-Ambient/tree/main
# background_fn: null    
# crop: True    # use alignment of model to crop

# - Uncomment to reconstruct plush parrot (direct capture)
fn: parrot_raw.png 
background_fn: parrot_background.png
rotate: False
alignment:
  dim: [160, 160]
  top_left: [110, 200]

## - Uncomment to reconstruct plush monkey (direct capture)
# fn: monkey_raw.png
# background_fn: monkey_background.png
# rotate: False
# alignment:
#   dim: [123, 123]
#   top_left: [118, 220]

## - Uncomment to reconstruct plant (direct capture)
# fn: plant_raw.png     
# background_fn: plant_background.png 
# rotate: False
# alignment:
#   dim: [200, 200]
#   top_left: [60, 186]

## Reconstruction
background_sub: True  # whether to subtract background

# -- for learning-based methods (uncommment one line)
model: Unet4M+U5+Unet4M_concat
# model: U5+Unet8M
# model: Unet4M+U5+Unet4M_learned_sub

# # -- for ADMM with fixed parameters (uncomment and comment learning-based methods)
# model: admm
n_iter: 100

device: cuda:0
n_trials: 1   # to get average inference time
save: True