# python scripts/eval/benchmark_recon.py -cn digicam_parameter_and_perturb
defaults:
  - defaults
  - _self_


dataset: HFDataset
batchsize: 1
device: "cuda:0"

huggingface:
  repo: "bezzam/DigiCam-Mirflickr-MultiMask-25K"
  psf: null   # null for simulating PSF
  image_res: [900, 1200]  # used during measurement
  rotate: True   # if measurement is upside-down
  flipud: False
  flip_lensed: False   # if rotate or flipud is True, apply to lensed
  alignment:
    top_left: [80, 100]  # height, width
    height: 200
  downsample: 1

algorithms: [
  "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave_psfNN",
  "hf:digicam:mirflickr_multi_25k:Unet4M+U5+Unet4M_wave_psfNN",
]

pnp:
  mu: 1e-3   # weight for distance from original model parameters
  model_path: null    # leave null to be overwritten in script
  # lr: 1e-2
  # n_iter: 10
  lr: 3e-3   # learning rate for SGD
  n_iter: 10   # number of iterations


save_idx: [1, 2, 4, 5, 9, 24, 33, 61]

# simulating PSF
simulation:
  use_waveprop: True
  deadspace: True
  scene2mask: 0.3
  mask2sensor: 0.002
