# python scripts/eval/benchmark_recon.py -cn digicam
defaults:
  - defaults
  - _self_

dataset: HFDataset
batchsize: 4
device: "cuda:0"

huggingface:
  repo: "bezzam/DigiCam-Mirflickr-SingleMask-25K"
  cache_dir: null
  psf: null   # null for simulating PSF
  image_res: [900, 1200]  # used during measurement
  rotate: True   # if measurement is upside-down
  flipud: False
  flip_lensed: False   # if rotate or flipud is True, apply to lensed
  alignment:
    top_left: [80, 100]  # height, width
    height: 200
  downsample: 1


algorithms: [
  # "ADMM",
  "ADMM",
  "ADMM_PnP",

  # # -- reconstructions trained on measured data
  # "hf:digicam:mirflickr_single_25k:U5+Unet8M_wave",
  # "hf:digicam:mirflickr_single_25k:Unet8M+U5_wave",
  # "hf:digicam:mirflickr_single_25k:TrainInv+Unet8M_wave",
  # "hf:digicam:mirflickr_single_25k:MMCN4M+Unet4M_wave",
  # "hf:digicam:mirflickr_single_25k:MWDN8M_wave",
  # "hf:digicam:mirflickr_single_25k:Unet4M+TrainInv+Unet4M_wave",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave",
  # "hf:digicam:mirflickr_single_25k:Unet2M+MMCN+Unet2M_wave",
  # "hf:digicam:mirflickr_single_25k:Unet2M+MWDN6M_wave",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U10+Unet4M_wave",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave_psfNN",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave_flips",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave_flips_rotate10",
  # "hf:digicam:mirflickr_single_25k:Unet8M_wave_v2",

  # ## -- reconstructions trained on other datasets/systems
  # "hf:diffusercam:mirflickr:Unet4M+U10+Unet4M",
  # "hf:tapecam:mirflickr:Unet4M+U10+Unet4M",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave",
  # "hf:digicam:celeba_26k:Unet4M+U5+Unet4M_wave",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M",
  # "hf:digicam:mirflickr_multi_25k:Unet4M+U5+Unet4M_wave",
  # "hf:digicam:mirflickr_multi_25k:Unet4M+U5+Unet4M_wave_psfNN",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_psfNN",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_psfNN",
]

# save_idx: [1, 2, 4, 5, 9, 24, 33, 61]
# n_iter_range: [100]    # for ADMM
save_idx: [1, 2, 4, 5, 9]
n_iter_range: [10]    # for ADMM

# simulating PSF
simulation:
  use_waveprop: True
  deadspace: True
  scene2mask: 0.3
  mask2sensor: 0.002
